#开发配置
spring:
  datasource:
    url: jdbc:mysql://10.161.24.233:3306/opst
    username: app
    password: app
    driver-class-name: com.mysql.jdbc.Driver
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource

mybatis:
  mapper-locations: classpath:mapping/*.xml