#开发配置
spring:
  datasource:
    url: jdbc:mysql://xxx.xxx.xx.xxx:3306/opst
    username: xxx
    password: xxx
    driver-class-name: com.mysql.jdbc.Driver
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource

mybatis:
  mapper-locations: classpath:mapping/*.xml