package com.example.demo334.dao;

import com.example.demo334.entity.HostInfo;
import com.example.demo334.entity.HostInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface HostInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table td_host_info
     *
     * @mbg.generated
     */
    long countByExample(HostInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table td_host_info
     *
     * @mbg.generated
     */
    int insert(HostInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table td_host_info
     *
     * @mbg.generated
     */
    int insertSelective(HostInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table td_host_info
     *
     * @mbg.generated
     */
    List<HostInfo> selectByExample(HostInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table td_host_info
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") HostInfo record, @Param("example") HostInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table td_host_info
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") HostInfo record, @Param("example") HostInfoExample example);
}