package com.example.demo334.entity;

import java.util.Date;

public class HostInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column td_host_info.domain
     *
     * @mbg.generated
     */
    private Byte domain;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column td_host_info.host_ip
     *
     * @mbg.generated
     */
    private String hostIp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column td_host_info.host_name
     *
     * @mbg.generated
     */
    private String hostName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column td_host_info.module
     *
     * @mbg.generated
     */
    private String module;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column td_host_info.module_name
     *
     * @mbg.generated
     */
    private String moduleName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column td_host_info.machine_model
     *
     * @mbg.generated
     */
    private String machineModel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column td_host_info.use_flag
     *
     * @mbg.generated
     */
    private Byte useFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column td_host_info.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column td_host_info.update_user
     *
     * @mbg.generated
     */
    private String updateUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column td_host_info.ontime
     *
     * @mbg.generated
     */
    private Date ontime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column td_host_info.oper_record
     *
     * @mbg.generated
     */
    private String operRecord;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column td_host_info.mroom
     *
     * @mbg.generated
     */
    private String mroom;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column td_host_info.domain
     *
     * @return the value of td_host_info.domain
     *
     * @mbg.generated
     */
    public Byte getDomain() {
        return domain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column td_host_info.domain
     *
     * @param domain the value for td_host_info.domain
     *
     * @mbg.generated
     */
    public void setDomain(Byte domain) {
        this.domain = domain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column td_host_info.host_ip
     *
     * @return the value of td_host_info.host_ip
     *
     * @mbg.generated
     */
    public String getHostIp() {
        return hostIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column td_host_info.host_ip
     *
     * @param hostIp the value for td_host_info.host_ip
     *
     * @mbg.generated
     */
    public void setHostIp(String hostIp) {
        this.hostIp = hostIp == null ? null : hostIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column td_host_info.host_name
     *
     * @return the value of td_host_info.host_name
     *
     * @mbg.generated
     */
    public String getHostName() {
        return hostName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column td_host_info.host_name
     *
     * @param hostName the value for td_host_info.host_name
     *
     * @mbg.generated
     */
    public void setHostName(String hostName) {
        this.hostName = hostName == null ? null : hostName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column td_host_info.module
     *
     * @return the value of td_host_info.module
     *
     * @mbg.generated
     */
    public String getModule() {
        return module;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column td_host_info.module
     *
     * @param module the value for td_host_info.module
     *
     * @mbg.generated
     */
    public void setModule(String module) {
        this.module = module == null ? null : module.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column td_host_info.module_name
     *
     * @return the value of td_host_info.module_name
     *
     * @mbg.generated
     */
    public String getModuleName() {
        return moduleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column td_host_info.module_name
     *
     * @param moduleName the value for td_host_info.module_name
     *
     * @mbg.generated
     */
    public void setModuleName(String moduleName) {
        this.moduleName = moduleName == null ? null : moduleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column td_host_info.machine_model
     *
     * @return the value of td_host_info.machine_model
     *
     * @mbg.generated
     */
    public String getMachineModel() {
        return machineModel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column td_host_info.machine_model
     *
     * @param machineModel the value for td_host_info.machine_model
     *
     * @mbg.generated
     */
    public void setMachineModel(String machineModel) {
        this.machineModel = machineModel == null ? null : machineModel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column td_host_info.use_flag
     *
     * @return the value of td_host_info.use_flag
     *
     * @mbg.generated
     */
    public Byte getUseFlag() {
        return useFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column td_host_info.use_flag
     *
     * @param useFlag the value for td_host_info.use_flag
     *
     * @mbg.generated
     */
    public void setUseFlag(Byte useFlag) {
        this.useFlag = useFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column td_host_info.update_time
     *
     * @return the value of td_host_info.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column td_host_info.update_time
     *
     * @param updateTime the value for td_host_info.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column td_host_info.update_user
     *
     * @return the value of td_host_info.update_user
     *
     * @mbg.generated
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column td_host_info.update_user
     *
     * @param updateUser the value for td_host_info.update_user
     *
     * @mbg.generated
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column td_host_info.ontime
     *
     * @return the value of td_host_info.ontime
     *
     * @mbg.generated
     */
    public Date getOntime() {
        return ontime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column td_host_info.ontime
     *
     * @param ontime the value for td_host_info.ontime
     *
     * @mbg.generated
     */
    public void setOntime(Date ontime) {
        this.ontime = ontime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column td_host_info.oper_record
     *
     * @return the value of td_host_info.oper_record
     *
     * @mbg.generated
     */
    public String getOperRecord() {
        return operRecord;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column td_host_info.oper_record
     *
     * @param operRecord the value for td_host_info.oper_record
     *
     * @mbg.generated
     */
    public void setOperRecord(String operRecord) {
        this.operRecord = operRecord == null ? null : operRecord.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column td_host_info.mroom
     *
     * @return the value of td_host_info.mroom
     *
     * @mbg.generated
     */
    public String getMroom() {
        return mroom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column td_host_info.mroom
     *
     * @param mroom the value for td_host_info.mroom
     *
     * @mbg.generated
     */
    public void setMroom(String mroom) {
        this.mroom = mroom == null ? null : mroom.trim();
    }
}